Update zh_CN.lang
GTNewHorizons/Angelica pull request #565
Opened 2024-07-21 15:38 UTC by NealDeal34

2024-07-24 03:25 UTC, Nxer requested changes

2024-07-24 03:25 UTC, Nxer commented on src/main/resources/assets/angelica/lang/zh_CN.lang
> +options.iris.shadowDistance.disabled=你不能改变当前光影包已经为阴影设置的渲染距离。
`当前光影包设置了阴影距离，无法修改。` 改成人话

2024-07-24 04:40 UTC, Hikari1nVoid requested changes
这么个长句没个逗号是否合适

2024-07-24 04:40 UTC, Hikari1nVoid commented on src/main/resources/assets/angelica/lang/zh_CN.lang
> +options.dynamic_lights.tooltip=启用动态光源. 模式选择: OFF - 关闭, FASTEST - 500ms延迟, FAST - 250ms延迟, FANCY - 无延迟. 如果正在使用光影则此功能被禁用.
`如果正在使用光影则此功能被禁用`-->`使用光影时此选项无效`
weird grammar...

2024-07-24 04:55 UTC, NealDeal34 commented on src/main/resources/assets/angelica/lang/zh_CN.lang
> +options.dynamic_lights.tooltip=启用动态光源. 模式选择: OFF - 关闭, FASTEST - 500ms延迟, FAST - 250ms延迟, FANCY - 无延迟. 如果正在使用光影则此功能被禁用.
Honestly, do you really know the differences between 'feature is disabled' and 'the state can't be changed'?

2024-07-25 00:54 UTC, mitchej123 commented
Will merge when a (native) Chinese Speaker approves - doesn't need to be a dev

2024-07-25 01:09 UTC, Dream-Master commented
@Kiwi233

2024-07-25 01:29 UTC, Hikari1nVoid reviewed
Please make sure the translation is compliant with local language culture.Otherwise spamming DeepL translator is sufficient.

2024-07-25 01:29 UTC, Hikari1nVoid commented on src/main/resources/assets/angelica/lang/zh_CN.lang
> +sodium.options.use_fog_occlusion.tooltip=如果启用，确定被雾效果完全遮挡的块将不会被渲染，有助于提高性能。当雾效果较重时（例如在水下时），提高可能会更加显著，但在某些情况下可能会导致天空和雾之间出现不良的视觉瑕疵。
please revert this one.original one sounds way more better.

2024-07-25 01:29 UTC, Hikari1nVoid commented on src/main/resources/assets/angelica/lang/zh_CN.lang
> +sodium.options.ignore_driver_blacklist.name=忽略驱动程序冲突
驱动程序黑名单 is a widely accepted when describing drivers with vulnerabilities and need to be blocked/blacklisted.
original is better

2024-07-25 01:29 UTC, Hikari1nVoid commented on src/main/resources/assets/angelica/lang/zh_CN.lang
> +options.iris.reset.tooltip.holdShift=按住 SHIFT 并点击以重置
original one is better.remember this is a tooltip.

2024-07-25 05:14 UTC, NealDeal34 commented on src/main/resources/assets/angelica/lang/zh_CN.lang
> +sodium.options.ignore_driver_blacklist.name=忽略驱动程序冲突
Did you just search for what '驱动程序黑名单' means? Or, as you say,it is used to describe 'vulnerabilities' or with unsafe signs that should be disabled, not the term 'incompatible' in this context.And it's cause misunderstand for players.Don't just literal translation“blacklist”，ok?

2024-07-25 05:16 UTC, NealDeal34 commented on src/main/resources/assets/angelica/lang/zh_CN.lang
> +sodium.options.ignore_driver_blacklist.name=忽略驱动程序冲突
Did you just search for what '驱动程序黑名单' means? Or, as you say,it is used to describe 'vulnerabilities' or with unsafe signs that should be disabled, not the term 'incompatible' in this context.And it's cause misunderstand for players.Don't just literal translate “blacklist”，ok?

2024-07-25 05:32 UTC, NealDeal34 commented
> Please make sure the translation is compliant with local language culture.Otherwise spamming DeepL translator is sufficient.

I didn't mean to offend you, but please don't make me question your Chinese proficiency, ok？It's obvious which one was machine translation,if you can't get it,perhaps we can seek clarification from someone else :)

2024-08-05 04:48 UTC, Dream-Master commented
@Nxer

2024-08-07 15:53 UTC, Hikari1nVoid commented
all good on commit e4128e01e54ff6f05212158e36c66d24807a9a66

2024-08-07 16:21 UTC, mitchej123 approved these changes

2024-08-17 10:56 UTC, Nxer approved these changes
No wrong words.

2024-08-17 15:05 UTC, merged